trigger:
  - main

pool:
  name: MyPool

variables:
  nodeVersion: "20.x"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)

          - powershell: npm install
            displayName: Install

          - powershell: npm run build
            displayName: Build
            env:
              REACT_APP_SECRET_KEY: $(REACT_APP_SECRET_KEY)

          - publish: build
            artifact: react-build

  - stage: DEV
    dependsOn: Build

    jobs:
      - job: ApproveDEV
        pool: server
        timeoutInMinutes: 43200
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: ""
              instructions: "Please approve deployment to DEV environment."
              onTimeout: reject
            timeoutInMinutes: 43200

      - deployment: DeployDEV
        dependsOn: ApproveDEV
        environment: DEV

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$env:FIREBASE_DEV_SERVICE_ACCOUNT" > firebase-dev.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-dev.json"

                    firebase use dev

                    firebase deploy --only hosting
                  displayName: Deploy DEV

  - stage: QA
    dependsOn: DEV

    jobs:
      - job: ApproveQA
        pool: server
        timeoutInMinutes: 43200
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: ""
              instructions: "Please approve deployment to QA environment."
              onTimeout: reject
            timeoutInMinutes: 43200

      - deployment: DeployQA
        dependsOn: ApproveQA
        environment: QA

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$env:FIREBASE_QA_SERVICE_ACCOUNT" > firebase-qa.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-qa.json"

                    firebase use qa

                    firebase deploy --only hosting
                  displayName: Deploy QA

  - stage: PROD
    dependsOn: QA

    jobs:
      - job: ApprovePROD
        pool: server
        timeoutInMinutes: 43200
        steps:
          - task: ManualValidation@0
            inputs:
              notifyUsers: ""
              instructions: "Please approve deployment to PROD environment."
              onTimeout: reject
            timeoutInMinutes: 43200

      - deployment: DeployPROD
        dependsOn: ApprovePROD
        environment: PROD

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$env:FIREBASE_PROD_SERVICE_ACCOUNT" > firebase-prod.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-prod.json"

                    firebase use prod

                    firebase deploy --only hosting
                  displayName: Deploy PROD
