trigger:
  - main

pool:
  name: MyPool

variables:
  - group: firebase-secrets

  - name: nodeVersion
    value: "20.x"

stages:
  # ================= BUILD =================
  - stage: Build
    displayName: Build React App

    jobs:
      - job: BuildJob
        displayName: Build

        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)

          - script: |
              npm install
            displayName: Install Dependencies

          - script: |
              npm run build
            displayName: Build React App

          - publish: build
            artifact: react-build

  # ================= DEV =================
  - stage: DEV
    displayName: Deploy DEV
    dependsOn: Build

    jobs:
      - deployment: DeployDEV
        environment: DEV

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: |

                    npm install -g firebase-tools

                    "$(FIREBASE_DEV_SERVICE_ACCOUNT)" | Out-File firebase-dev.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-dev.json"

                    cd "$(System.DefaultWorkingDirectory)"

                    firebase deploy --only hosting --project dev

                  displayName: Deploy Firebase DEV

  # ================= QA =================
  - stage: QA
    displayName: Deploy QA
    dependsOn: DEV

    jobs:
      - deployment: DeployQA
        environment: QA

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: |

                    npm install -g firebase-tools

                    "$(FIREBASE_QA_SERVICE_ACCOUNT)" | Out-File firebase-qa.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-qa.json"

                    cd "$(System.DefaultWorkingDirectory)"

                    firebase deploy --only hosting --project qa

                  displayName: Deploy Firebase QA

  # ================= PROD =================
  - stage: PROD
    displayName: Deploy PROD
    dependsOn: QA

    jobs:
      - deployment: DeployPROD
        environment: PROD

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: |

                    npm install -g firebase-tools

                    "$(FIREBASE_PROD_SERVICE_ACCOUNT)" | Out-File firebase-prod.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-prod.json"

                    cd "$(System.DefaultWorkingDirectory)"

                    firebase deploy --only hosting --project prod

                  displayName: Deploy Firebase PROD
