trigger:
  - main

pool:
  name: MyPool

variables:
  nodeVersion: "20.x"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)

          - powershell: npm install
            displayName: Install

          - powershell: npm run build
            displayName: Build

          - publish: build
            artifact: react-build

  - stage: DEV
    dependsOn: Build

    jobs:
      - deployment: DeployDEV
        environment: DEV

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$(FIREBASE_DEV_SERVICE_ACCOUNT)" > firebase-dev.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-dev.json"

                    firebase use dev

                    firebase deploy --only hosting
                  displayName: Deploy DEV

  - stage: QA
    dependsOn: DEV

    jobs:
      - deployment: DeployQA
        environment: QA

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$(FIREBASE_QA_SERVICE_ACCOUNT)" > firebase-qa.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-qa.json"

                    firebase use qa

                    firebase deploy --only hosting
                  displayName: Deploy QA

  - stage: PROD
    dependsOn: QA

    jobs:
      - deployment: DeployPROD
        environment: PROD

        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: react-build

                - powershell: npm install -g firebase-tools

                - powershell: |
                    echo "$(FIREBASE_PROD_SERVICE_ACCOUNT)" > firebase-prod.json

                    $env:GOOGLE_APPLICATION_CREDENTIALS="firebase-prod.json"

                    firebase use prod

                    firebase deploy --only hosting
                  displayName: Deploy PROD
